### ISSUE TITLE
I am facing a weird issue, and not sure if its a bug related to state 

### ISSUE THREAD

**Issue by tushar4303** [maheshmnj/navbar_router#16]
**Describe the bug**
When i switch pages some of the options from page 1 gets shown in page 2, or sometimes all the options are replaced with options in page 1 and vice versa and it gets back to normal when i refresh the page.

Earlier i thought this must have been a problem with the data source (json get in this case) but since this is only happening partially, i.e only the options or sometimes the cards itself and even half of the options when are actually hardcoded into ui is displayed in different page.

So i couldn't exactly figure out what exactly the issue was 

**To Reproduce**
1. Open the app
2. Change screens
3. Go back to a different screen (happens occasionally)
4. Or close the app and relaunch it from recent apps (from memory) and on refresh everything gets back to normal

**Expected behavior**
Options and the posts to be displayed on their respective page, but somehow it gets mixed in this case 

**Screenshots**
<img src="https://user-images.githubusercontent.com/88235295/210273253-d9cc5fde-2954-4efd-b8c7-92ed34d61883.jpg" width="250" />
This is the correct layout of notifications

<img src="https://user-images.githubusercontent.com/88235295/210273268-61237713-f9ea-4563-94a8-8078e59bc5d0.jpg" width="250" />

But in this case its listing options from events page (technical, sports, cultural) 

<img src="https://user-images.githubusercontent.com/88235295/210273297-8febde74-2fea-43ae-bcea-bce5a45142f5.jpg" width="250" />

This is the actual layout of events page

<img src="https://user-images.githubusercontent.com/88235295/210273311-e42f2983-090d-4a94-aea8-01ae6dede5e6.jpg" width="250" />

But in this case, the first option (hard coded on which is supposed to show when i tap technical) shows up but rest of the options are from notifications page 

The same happens with posts too sometimes 

**Desktop:**
 - OS: windows 11 
 - Browser Edge 
 

**Smartphone:**
 - Device: Redmi note 11 
 - OS: Android 12
 

**Additional context**
I tried rebuilding, flutter clean etc but this issue persists.

**Comment by maheshmnj** [comment]
Hi, @tushar4303 Thanks for reporting, If I understand it right by options you are referring to the List of chips is it?

<img width="513" alt="Screenshot 2023-01-02 at 5 38 01 PM" src="https://user-images.githubusercontent.com/31410839/210282491-f2d1af1c-4681-4d27-9281-ed668db7dbbc.png">


Can you share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) to address the issue better ? 

 You could also take the [example app](https://github.com/maheshmnj/navbar_router/blob/main/example/lib/main.dart), modify it, and share the reproducible code

**Comment by tushar4303** [comment]
<script src="https://gist.github.com/nisrulz/11c0d63428b108f10c83.js"></script>

**Comment by tushar4303** [comment]
@maheshmnj sorry to bother again, but i just wanted to know whether the issue is with my code, which is causing this bug?

**Comment by tushar4303** [comment]
Maybe since i was using the same base class model for both the pages, the state somehow got messed up when paired with the nav bar.

However on migrating to different data class model, fixed the problem.

I am closing this issue for now.

**Comment by maheshmnj** [comment]
Glad you were able to solve it!
