### ISSUE TITLE
Navbar Height is too much on Android and IOS

### ISSUE THREAD

**Issue by maheshmnj** [maheshmnj/navbar_router#17]
**Describe the bug**
Investigate the bottom nav bar height in material specs

**To Reproduce**
1. Run the example app on an Android
2. check the navbar height

**Expected behavior**
Height should match the standard material guidelines

**Screenshots**
Pixel 7            |  Xiaomi k20 pro
:-------------------------:|:-------------------------:
![flutter_03](https://github.com/maheshmnj/navbar_router/assets/31410839/0da9a26e-2797-4652-9cc7-37829f502ad1) | ![flutter_01](https://github.com/maheshmnj/navbar_router/assets/31410839/940d4251-b8c6-4335-9470-6d12189a1d15)

**Comment by maheshmnj** [comment]
This is a bug in flutter's NavigationBar https://github.com/flutter/flutter/issues/127088

**Comment by maheshmnj** [comment]
### IOS

<img width="328" alt="image" src="https://github.com/maheshmnj/navbar_router/assets/31410839/02281da7-20f5-414a-9ba5-35ff39b3f74d">

**Comment by maheshmnj** [comment]
Fixed in release [v0.6.2](https://pub.dev/packages/navbar_router/changelog)

**Comment by karatekid430** [comment]
Seriously the bottom value is twice what it should be. It leaves a massive gap above the system nav bar. I want just the height of the nav bar and if I want more space then I should be using a padding.

<img width="455" alt="imagen" src="https://github.com/maheshmnj/navbar_router/assets/11409127/a8fe3812-5137-4c0d-b662-f1a62b2bd136">

```Dart
                bottomNavigationBar: TabBar(
                  tabs: const [
                    Tab(
                      icon: Icon(Icons.directions_car),
                      text: 'Car',
                    ),
                    Tab(
                      icon: Icon(Icons.directions_transit),
                      text: 'Transit',
                    ),
                    Tab(
                      icon: Icon(Icons.person),
                      text: 'Account',
                    ),
                  ],
                  padding: EdgeInsets.only(
                    bottom: MediaQuery.paddingOf(context).bottom,
                  ),
                  dividerColor: Colors.transparent,
                ),
```

**Comment by maheshmnj** [comment]
Hi @karatekid430, I wonder if the issue you are referring to is relatd to navbar_router package?
