### ISSUE TITLE
Stacking a widget on top of an existing navigation stack with the wrong navbar item highlighted

### ISSUE THREAD

**Issue by tushar4303** [maheshmnj/navbar_router#21]
**Describe the bug**
When the notifications are sent from Firebase fcm, the tap event of the notification is expected to navigate to the notification page. That is happening correctly, however the navbar item that is being highlighted is not in accordance with the widget being shown since the notification page is shown on top of the homepage and requires a double tap to go back to the homepage, which is actually correct for how this package should behave. However, my application has 4 screens: home, notification, explore, and profile, where the 1st screen is home followed by notification, but on tapping homepage, the notification page is displayed with homepage being highlighted. So is there a solution wherein on tapping the notification, the second navbar item is highlighted, i.e., the notifications page?

**To Reproduce**
1. click on the notification
2. the app opens with homepage being replaced with notification while the homepage navbar icon is highlighted
3. double tap on homeicon to go back to homepage

**Expected behavior**
Not exactly expected, since this is actually how this package intends to work however iIrequest you to please provide a workaround or a solution to my problem if possible.

**Screen recording**

https://user-images.githubusercontent.com/88235295/224127135-c8c6c0bf-2b83-4527-bd3b-b43b5d779e25.mp4

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Microsoft Edge

 - Device: Redmi note 11
 - OS: android 12
 

is there an approach where when i tap on the notification i go to notification page with the same icon being highlighted?

btw here is the code:

```
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        navigatorKey: navigatorKey,
        scaffoldMessengerKey: snackbarKey,
        themeMode: ThemeMode.light,
        debugShowCheckedModeBanner: false,
        theme: MyTheme.lightTheme(context),
        darkTheme: MyTheme.darkTheme(context),
        // home: HomePage(),
        // home: MyPhone(),
        home: isLoggedIn ? HomePage() : LoginPage()
        // initialRoute: isLoggedIn ? HomePage() : LoginPage();
        );
  }
}

class HomePage extends StatelessWidget {
  HomePage({Key? key}) : super(key: key);

  List<NavbarItem> items = [
    NavbarItem(
      Icons.home,
      'Home',
    ),
    NavbarItem(
      Icons.notifications,
      'Notifications',
    ),
    NavbarItem(Icons.explore, 'Explore'),
    NavbarItem(Icons.person, 'Profile'),
  ];

  final Map<int, Map<String, Widget>> _routes = {
    0: {
      '/': HomeScreen(),
    },
    1: {
      '/': NotificationPage(),
    },
    2: {
      '/': MyEvents(),
    },
    3: {
      '/': MyProfile(),
    },
  };

  @override
  Widget build(BuildContext context) {
    return NavbarRouter(
      errorBuilder: (context) {
        return const Center(child: Text('Error 404'));
      },
      onBackButtonPressed: (isExiting) {
        return isExiting;
      },
      destinationAnimationCurve: Curves.fastOutSlowIn,
      destinationAnimationDuration: 700,
      decoration: NavbarDecoration(
          backgroundColor: const Color.fromRGBO(251, 251, 252, 1),
          selectedIconTheme: const IconThemeData(color: Colors.black),
          navbarType: BottomNavigationBarType.fixed,
          elevation: 18,
          selectedLabelTextStyle: const TextStyle(color: Colors.black),
          enableFeedback: true),
      destinations: [
        for (int i = 0; i < items.length; i++)
          DestinationRouter(
            navbarItem: items[i],
            destinations: [
              for (int j = 0; j < _routes[i]!.keys.length; j++)
                Destination(
                  route: _routes[i]!.keys.elementAt(j),
                  widget: _routes[i]!.values.elementAt(j),
                ),
            ],
            // initialRoute: _routes[i]!.keys.first,
          ),
      ],
    );
  }
}

// ignore_for_file: prefer_const_constructors`

```

and the part to push notificationpage to the stack:
```
FirebaseMessaging.onMessageOpenedApp.listen((RemoteMessage message) {
      if (message.notification != null) {
        print('idhar: click hua');
        // Notifications notification = Notifications.fromMap(message.data);
        print(message.data);

        Navigator.of(context).push(
          MaterialPageRoute(builder: (context) => const NotificationPage()),
        );
      }
    });
```

**Comment by maheshmnj** [comment]
Hi @tushar4303, Thanks for filing the issue. You could use the NavbarNotifier and manually set the index 

e.g
```dart
NavbarNotifier.index = 3; // changes the index programmatically
``` 

Would this help achieve your use case?

**Comment by tushar4303** [comment]
So in the main.dart file i have a home widget which has all the navbar configuration which loads up the home screen by default which is index 0, so let's say i pass navbar notifier's index as 1 and do navigation.push() , so would i still have to press the notification button twice? Because it would still be pushed on top of the existing navigation stack right? 

Also i was wondering how I can show the badge on the notification icon as the number of unread notifications, if that's possible

**Comment by maheshmnj** [comment]
> So in the main.dart file i have a home widget that has all the navbar configuration which loads up the home screen by default which is index 0, so let's say i pass navbar notifier's index as 1 and do navigation.push()

When you do `NavbarNotifier.index = 1` you don't need to push any widget on the stack, unless you want to.

> so would i still have to press the notification button twice? Because it would still be pushed on top of the existing navigation stack which will already have a notification page below it, right. Or there's no need to push a new screen only changing index, does the work?

Good question! I have a helper method `navigate` which has a parameter `isRootNavigator`, setting it to `false` will push the route on top of the current NavigatorStack (onTop of NavbarRouter, not the Flutter's navigator stack), Perhaps I should clarify this further in the docs. 
https://github.com/maheshmnj/navbar_router/blob/b3496ace8c2f1731ee244806b5deaa45d1955dca/lib/src/navbar_router.dart#L327-L332

 for instance

if you are on index 1, if you call 
```dart
navigate(context, HomePage(), isRootNavigator: true)
```

You will push HomePage to flutter's NavigatorStack (on top of this NavbarRouter WIdget), But instead, if you set that to `false`

```dart
navigate(context, HomePage(), isRootNavigator: false)
``` 
You will push the widget on top of the current NestedNavigator (Within NavbarRouter) i.e on Top of the second Navigator since each tab is a Nested Navigator.

So when you tap on the Notification, You could do one of these based on whether you want to show the BottomNavigationBar
1. if you want to keep the NavigationBar, change the index to 1 which should switch the tab to the notifications page (With the old State), You will need to update the state though (Perhaps NavbarRouter should have a event listener)

2. if you don't want to show the NavigationBar You could push NotificationsPage on top of flutter's Navigator stack (Assuming the BottomNavigationBar is hidden and the user can exit NotificationsPage via the back button in the appBar)
You could also hide the NavigationBar in point 1 using `NavbarNotifier.hideBottomNavBar = true;`

**Comment by maheshmnj** [comment]
Let me know if you have any further questions about NavbarRouter and I will try to answer them, Thanks btw this really helps me to improve the NavbarRouter through different use cases.

**Comment by maheshmnj** [comment]
Note for self
- Add an index change Listener
- Document how routes are pushed on top of each tab and flutter's Navigator stack.

**Comment by tushar4303** [comment]
thanks a lot! this package has indeed helped me save a ton of time.
