### ISSUE TITLE
Support for badges on the NavbarItem

### ISSUE THREAD

**Issue by maheshmnj** [maheshmnj/navbar_router#30]
**Is your feature request related to a problem? Please describe.**
Users would like to show a notification badge on a NavbarItem

**Describe the solution you'd like**
 NavbarItem should have a property to show a red  dot on top

**Comment by maheshmnj** [comment]
Merged in https://github.com/maheshmnj/navbar_router/pull/43/

**Comment by maheshmnj** [comment]
Keeping this open until we update the docs https://docs.maheshjamdade.com/navbar_router/

**Comment by bebaoboy** [comment]
Yay thank you for informing me about the release 😆 I'm a bit struggling with school projects recently and will be back soon!
Have a nice day @maheshmnj !

**Comment by maheshmnj** [comment]
No worries take you time. Good luck luck with your school work you will do great.

**Comment by maheshmnj** [comment]
Docs have been updated: http://localhost:3000/navbar_router/features#animated-navbar-badges
