### ISSUE TITLE
Back Button History Bug

### ISSUE THREAD

**Issue by bebaoboy** [maheshmnj/navbar_router#51]
**Edited**
This bug also presents on the web demo [Navbar Router Netlify](https://navbar-router.netlify.app/)
<br><br>

**Describe the bug**
- **After trying to fix #50** like I suggested in the link, I run the app like normal and got this bug: pressing back button won't return to previous tab
- Plus, there's no snackbar showing when exit the app.

https://github.com/maheshmnj/navbar_router/assets/74720131/ab6cf0a9-8569-4c13-8447-76027f9b51a0

**To Reproduce**

**Smartphone (please complete the following information):**
 - Device: Xiaomi 11T
 - OS: Android 14
 - Flutter 3.22.0

**Comment by bebaoboy** [comment]
- Fyi: I was doing the #48 on my branch and got this bug, so I have to re-run the code from the official (main) branch to confirm it.

**Comment by maheshmnj** [comment]
Fixed and released in [v0.7.5](https://pub.dev/packages/navbar_router/changelog)
