### ISSUE TITLE
indexChangeListerner bug

### ISSUE THREAD

**Issue by bebaoboy** [maheshmnj/navbar_router#53]
Hello I think I found a bug.

When pressing back button to navigate back to the previous tab (with `BackButtonBehavior.rememberHistory`), the `_indexChangeListerner` won't fire. 

I believe it's in this code, 

``` dart
if (behavior == BackButtonBehavior.rememberHistory) {
    if (_navbarStackHistory.length > 1) {
      _navbarStackHistory.removeLast();
      _index = _navbarStackHistory.last;     // <--- this one should be changed
      _singleton.notify();
      exitingApp = false;
    } 

```

the private variable `_index` should be `index` (where everything related to index change gets noticed):

``` dart
  static set index(int x) {
    _index = x;
    if (hideBadgeOnPageChanged) makeBadgeVisible(x, false);
    if (_navbarStackHistory.contains(x)) {
      _navbarStackHistory.remove(x);
    }
    _navbarStackHistory.add(x);
    _notifyIndexChangeListeners(x);
    _singleton.notify();
  }
```

**Comment by maheshmnj** [comment]
Hi @bebaoboy Thanks for filing the issue. I think the code is correct, The back button click to change index was fixed last week It should work on the latest version 0.7.5 let me know if it doesn't

ps: Please use \``` your code here\``` to share code instead of images as it allows to copy and modify

**Comment by bebaoboy** [comment]
Hello @maheshmnj , I just checked and confirmed that I'm on the source code of version 0.7.5. And this bug is not the same as the one in your PR 4 days ago. It's still there...

Proof I'm using version 0.7.5:
![image](https://github.com/user-attachments/assets/dc8c8e3b-8019-43f1-99ac-2d7d718b7db1)

**Comment by maheshmnj** [comment]
> When pressing back button to navigate back to the previous tab (with BackButtonBehavior.rememberHistory), the _indexChangeListerner won't fire.

Oh I see, I missed this part sorry, the indexChangeListened won't fire on back button (It does change tabs) got it.

**Comment by maheshmnj** [comment]
Fixed should be available in next release
