### ISSUE TITLE
Double tap on Navbar item to refresh tab

### ISSUE THREAD

**Issue by bebaoboy** [maheshmnj/navbar_router#54]
Feature request: User should be allowed to perform double-tap on an item on the navbar to refresh (rebuild) the page. 

It is true that they can implement this themselves using the `onCurrentTabClicked` callback, but should we allow them to have this built-in feature?

And I think it's not hard to implement that. Thanks for reading.

**Comment by maheshmnj** [comment]
What do you mean by refresh, resetting the state?  I think add such api could make the package bloated, I think its best to leave `onCurrentTabClicked` as is

**Comment by bebaoboy** [comment]
Okay, it's just my suggestion 😄

**Comment by maheshmnj** [comment]
Thanks for the suggestion, I think we don't need this feature as of now closing as invalid.
